DROP VIEW SIBDBA.V_ATTRIBUTE_ACCURACY;

/* Formatted on 2013/12/23 10:50:53 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_ATTRIBUTE_ACCURACY
(
   TY_PRODUIT,
   IDENTIFIANT,
   ED,
   VER,
   VALUE,
   EXPLANATION,
   LIEN
)
AS
   SELECT TY_PRODUIT,
          IDENTIFIANT,
          ED,
          VER,
          VALUE,
          EXPLANATION,
          TY_PRODUIT || '-' || IDENTIFIANT || '-' || ED || '.' || VER
     FROM F235_AT;

COMMENT ON TABLE SIBDBA.V_ATTRIBUTE_ACCURACY IS 'COMMENTAIRE:
Vue permettant de montrer les métadonnées de type ATTRIBUTE_ACCURACY.';



CREATE OR REPLACE PUBLIC SYNONYM V_ATTRIBUTE_ACCURACY FOR SIBDBA.V_ATTRIBUTE_ACCURACY;


GRANT SELECT ON SIBDBA.V_ATTRIBUTE_ACCURACY TO MDDTN;

GRANT SELECT ON SIBDBA.V_ATTRIBUTE_ACCURACY TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_ATTRIBUTE_ACCURACY TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_ATTRIBUTE_ACCURACY TO SIBMAJ;
