DROP VIEW V_CODES_ELEMENTS;

CREATE OR REPLACE FORCE VIEW V_CODES_ELEMENTS
(
   NO_MAP,
   CD_ELEM_TOPO,
   NOM,
   COLLISION_ACTIVE
)
AS
   SELECT CAST (PS.NO_MAP AS NUMBER (10)), 
          LE.CD_ELEM_TOPO, 
          EB.DESCR AS NOM, 
          LE.COLLISION_ACTIVE
     FROM F502_PS PS,
          F502_LE LE, 
          F132_EN EN, 
          F132_EB EB
    WHERE PS.NO_MAP=LE.NO_MAP 
      AND LE.CD_ELEM_TOPO=EN.CD_ELEM_TOPO
      AND EN.CD_ELEM_TOPO=EB.CD_ELEM_TOPO 
      AND PS.NORMES=EN.NORMES
 ORDER BY LE.NO_MAP,LE.CD_ELEM_TOPO DESC;

COMMENT ON TABLE V_CODES_ELEMENTS IS 'COMMENTAIRE:
Vue permettant de montrer les codes d''éléments touchés par la production.';



CREATE OR REPLACE PUBLIC SYNONYM V_CODES_ELEMENTS FOR V_CODES_ELEMENTS;


GRANT SELECT ON V_CODES_ELEMENTS TO MDDTN;

GRANT SELECT ON V_CODES_ELEMENTS TO SIBLIRE;

GRANT SELECT ON V_CODES_ELEMENTS TO SIBLIREDIFF;

GRANT SELECT ON V_CODES_ELEMENTS TO SIBMAJ;
