DROP VIEW SIBDBA.V_DEPTH_SYSTEM;

/* Formatted on 2013/12/23 10:51:52 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_DEPTH_SYSTEM
(
   TY_PRODUIT,
   IDENTIFIANT,
   ED,
   VER,
   DATUM_NAME,
   DISTANCE_UNITS,
   ENCODING_METHOD,
   RESOLUTION,
   LIEN
)
AS
   SELECT A.TY_PRODUIT,
          A.IDENTIFIANT,
          A.ED,
          A.VER,
          A.DATUM_NAME,
          A.DISTANCE_UNITS,
          A.ENCODING_METHOD,
          B.RESOLUTION,
          A.TY_PRODUIT || '-' || A.IDENTIFIANT || '-' || A.ED || '.' || A.VER
     FROM F235_DS A, F235_DR B
    WHERE     A.TY_PRODUIT = B.TY_PRODUIT
          AND A.IDENTIFIANT = B.IDENTIFIANT
          AND A.ED = B.ED
          AND A.VER = B.VER;

COMMENT ON TABLE SIBDBA.V_DEPTH_SYSTEM IS 'COMMENTAIRE:
Vue permettant de montrer les métadonnées de type DEPTH_SYSTEM.';



CREATE OR REPLACE PUBLIC SYNONYM V_DEPTH_SYSTEM FOR SIBDBA.V_DEPTH_SYSTEM;


GRANT SELECT ON SIBDBA.V_DEPTH_SYSTEM TO MDDTN;

GRANT SELECT ON SIBDBA.V_DEPTH_SYSTEM TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_DEPTH_SYSTEM TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_DEPTH_SYSTEM TO SIBMAJ;
