DROP VIEW SIBDBA.V_EXTENSION_NC;

/* Formatted on 2013/12/23 10:54:13 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_EXTENSION_NC
(
   NO_NC,
   DATE_ECH,
   RESP_ECH,
   NOTE
)
AS
   SELECT NO_ENREG,
          DATE_ECH,
          RESP_ECH,
          NOTE
     FROM F703_EX
    WHERE TYPE_ISO = 'NC';

COMMENT ON TABLE SIBDBA.V_EXTENSION_NC IS 'COMMENTAIRE:
Vue permettant de montrer les extensions des non-conformités.';



CREATE OR REPLACE PUBLIC SYNONYM V_EXTENSION_NC FOR SIBDBA.V_EXTENSION_NC;


GRANT SELECT ON SIBDBA.V_EXTENSION_NC TO MDDTN;

GRANT SELECT ON SIBDBA.V_EXTENSION_NC TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_EXTENSION_NC TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_EXTENSION_NC TO SIBMAJ;
