DROP VIEW SIBDBA.V_EXTENSION_AC;

/* Formatted on 2013/12/23 10:53:19 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_EXTENSION_AC
(
   NO_AC,
   DATE_ECH,
   RESP_ECH,
   NOTE
)
AS
   SELECT NO_ENREG,
          DATE_ECH,
          RESP_ECH,
          NOTE
     FROM F703_EX
    WHERE TYPE_ISO = 'ACTION';

COMMENT ON TABLE SIBDBA.V_EXTENSION_AC IS 'COMMENTAIRE:
Vue permettant de montrer les extensions des actions correctives.';



CREATE OR REPLACE PUBLIC SYNONYM V_EXTENSION_AC FOR SIBDBA.V_EXTENSION_AC;


GRANT SELECT ON SIBDBA.V_EXTENSION_AC TO MDDTN;

GRANT SELECT ON SIBDBA.V_EXTENSION_AC TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_EXTENSION_AC TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_EXTENSION_AC TO SIBMAJ;
