DROP VIEW SIBDBA.V_GEOGRAPHIC_RESOLUTION;

/* Formatted on 2013/12/23 10:55:15 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_GEOGRAPHIC_RESOLUTION
(
   TY_PRODUIT,
   IDENTIFIANT,
   ED,
   VER,
   LATITUDE_RES,
   LONGITUDE_RES,
   COORDINATE_UNITS,
   LIEN
)
AS
   SELECT TY_PRODUIT,
          IDENTIFIANT,
          ED,
          VER,
          LATITUDE_RES,
          LONGITUDE_RES,
          COORDINATE_UNITS,
          TY_PRODUIT || '-' || IDENTIFIANT || '-' || ED || '.' || VER
     FROM F235_GE;

COMMENT ON TABLE SIBDBA.V_GEOGRAPHIC_RESOLUTION IS 'COMMENTAIRE:
Vue permettant de montrer les métadonnées de type GEOGRAPHIC_RESOLUTION.';



CREATE OR REPLACE PUBLIC SYNONYM V_GEOGRAPHIC_RESOLUTION FOR SIBDBA.V_GEOGRAPHIC_RESOLUTION;


GRANT SELECT ON SIBDBA.V_GEOGRAPHIC_RESOLUTION TO MDDTN;

GRANT SELECT ON SIBDBA.V_GEOGRAPHIC_RESOLUTION TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_GEOGRAPHIC_RESOLUTION TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_GEOGRAPHIC_RESOLUTION TO SIBMAJ;
