DROP VIEW SIBDBA.V_GEODETIC_MODEL;

/* Formatted on 2013/12/23 10:54:42 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_GEODETIC_MODEL
(
   TY_PRODUIT,
   IDENTIFIANT,
   ED,
   VER,
   HORIZ_DATUM,
   ELLIPSOID,
   SEMI_MAJOR,
   DENOM_FLAT_RATIO,
   LIEN
)
AS
   SELECT TY_PRODUIT,
          IDENTIFIANT,
          ED,
          VER,
          HORIZ_DATUM,
          ELLIPSOID,
          SEMI_MAJOR,
          DENOM_FLAT_RATIO,
          TY_PRODUIT || '-' || IDENTIFIANT || '-' || ED || '.' || VER
     FROM F235_GM;

COMMENT ON TABLE SIBDBA.V_GEODETIC_MODEL IS 'COMMENTAIRE:
Vue permettant de montrer les métadonnées de type GEODETIC_MODEL.';



CREATE OR REPLACE PUBLIC SYNONYM V_GEODETIC_MODEL FOR SIBDBA.V_GEODETIC_MODEL;


GRANT SELECT ON SIBDBA.V_GEODETIC_MODEL TO MDDTN;

GRANT SELECT ON SIBDBA.V_GEODETIC_MODEL TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_GEODETIC_MODEL TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_GEODETIC_MODEL TO SIBMAJ;
