DROP VIEW SIBDBA.V_HORIZONTAL_ACCURACY;

/* Formatted on 2013/12/23 10:56:06 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_HORIZONTAL_ACCURACY
(
   TY_PRODUIT,
   IDENTIFIANT,
   ED,
   VER,
   REPORT,
   NO_SEQ,
   VALUE,
   EXPLANATION,
   LIEN
)
AS
   SELECT A.TY_PRODUIT,
          A.IDENTIFIANT,
          A.ED,
          A.VER,
          A.REPORT,
          B.NO_SEQ,
          B.VALUE,
          B.EXPLANATION,
          A.TY_PRODUIT || '-' || A.IDENTIFIANT || '-' || A.ED || '.' || A.VER
     FROM F235_PH A, F235_AH B
    WHERE     A.TY_PRODUIT = B.TY_PRODUIT
          AND A.IDENTIFIANT = B.IDENTIFIANT
          AND A.ED = B.ED
          AND A.VER = B.VER;

COMMENT ON TABLE SIBDBA.V_HORIZONTAL_ACCURACY IS 'COMMENTAIRE:
Vue permettant de montrer les métadonnées de type HORIZONTAL_ACCURACY.';



CREATE OR REPLACE PUBLIC SYNONYM V_HORIZONTAL_ACCURACY FOR SIBDBA.V_HORIZONTAL_ACCURACY;


GRANT SELECT ON SIBDBA.V_HORIZONTAL_ACCURACY TO MDDTN;

GRANT SELECT ON SIBDBA.V_HORIZONTAL_ACCURACY TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_HORIZONTAL_ACCURACY TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_HORIZONTAL_ACCURACY TO SIBMAJ;
