DROP VIEW SIBDBA.V_LIAISON_AC;

/* Formatted on 2013/12/23 10:56:36 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_LIAISON_AC
(
   NO_NC,
   NO_ACTION
)
AS
   SELECT NO_NC, NO_ACTION
     FROM F704_LI
    WHERE TY_LIEN = 'AC';

COMMENT ON TABLE SIBDBA.V_LIAISON_AC IS 'COMMENTAIRE:
Vue permettant de montrer les liens entre les non-conformités et les actions correctives.';



CREATE OR REPLACE PUBLIC SYNONYM V_LIAISON_AC FOR SIBDBA.V_LIAISON_AC;


GRANT SELECT ON SIBDBA.V_LIAISON_AC TO MDDTN;

GRANT SELECT ON SIBDBA.V_LIAISON_AC TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_LIAISON_AC TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_LIAISON_AC TO SIBMAJ;
