DROP VIEW SIBDBA.V_LIAISON_NC;

/* Formatted on 2013/12/23 10:57:04 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_LIAISON_NC
(
   NO_NC,
   NO_ACTION
)
AS
   SELECT NO_NC, NO_ACTION
     FROM F704_LI
    WHERE TY_LIEN = 'NC'
   UNION ALL
   SELECT NO_ACTION, NO_NC
     FROM F704_LI
    WHERE TY_LIEN = 'NC';

COMMENT ON TABLE SIBDBA.V_LIAISON_NC IS 'COMMENTAIRE:
Vue permettant de montrer les liens entre les non-conformités.';



CREATE OR REPLACE PUBLIC SYNONYM V_LIAISON_NC FOR SIBDBA.V_LIAISON_NC;


GRANT SELECT ON SIBDBA.V_LIAISON_NC TO MDDTN;

GRANT SELECT ON SIBDBA.V_LIAISON_NC TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_LIAISON_NC TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_LIAISON_NC TO SIBMAJ;
