DROP VIEW SIBDBA.V_NON_CONFORMITE;

/* Formatted on 2013/12/23 10:58:46 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_NON_CONFORMITE
(
   NO_NC,
   TY_PRODUIT,
   IDENTIFIANT,
   ED_DEBUT,
   VER_DEBUT,
   ED_FIN,
   VER_FIN,
   TY_NC,
   ORIGINE_NC,
   TITRE,
   TITRE_AN,
   NOM_SOURCE,
   DESCR,
   RESP_DESCR,
   CAUSE,
   DATE_SAISIE,
   TRAITEMENT,
   DATE_TRAITEMENT,
   RESP_CORR,
   SUIVI_TRAIT,
   RESP_SUIVI,
   TY_TRAIT_NC,
   ECHEANCE_INIT,
   DATE_FERMETURE,
   DOC_CONNEXE
)
AS
   SELECT F705_PR.NO_NC,
          TY_PRODUIT,
          IDENTIFIANT,
          ED_DEBUT,
          VER_DEBUT,
          ED_FIN,
          VER_FIN,
          F702_NC.TY_NC,
          ORIGINE_NC,
          TITRE,
          TITRE_AN,
          NOM_SOURCE,
          DESCR,
          RESP_DESCR,
          CAUSE,
          DATE_SAISIE,
          TRAITEMENT,
          DATE_TRAITEMENT,
          RESP_CORR,
          SUIVI_TRAIT,
          RESP_SUIVI,
          TY_TRAIT_NC,
          ECHEANCE_INIT,
          DATE_FERMETURE,
          DOC_CONNEXE
     FROM F705_PR, F702_NC
    WHERE F705_PR.NO_NC = F702_NC.NO_NC;

COMMENT ON TABLE SIBDBA.V_NON_CONFORMITE IS 'COMMENTAIRE:
Vue permettant de montrer les non-conformités.';



CREATE OR REPLACE PUBLIC SYNONYM V_NON_CONFORMITE FOR SIBDBA.V_NON_CONFORMITE;


GRANT SELECT ON SIBDBA.V_NON_CONFORMITE TO MDDTN;

GRANT SELECT ON SIBDBA.V_NON_CONFORMITE TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_NON_CONFORMITE TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_NON_CONFORMITE TO SIBMAJ;
