DROP VIEW SIBDBA.V_ONLINE_LINKAGE;

/* Formatted on 2013/12/23 10:59:44 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_ONLINE_LINKAGE
(
   TY_PRODUIT,
   IDENTIFIANT,
   ED,
   VER,
   ONLINE_LINKAGE,
   LIEN
)
AS
   SELECT TY_PRODUIT,
          IDENTIFIANT,
          ED,
          VER,
          ONLINE_LINKAGE,
          TY_PRODUIT || '-' || IDENTIFIANT || '-' || ED || '.' || VER
     FROM F235_OL;

COMMENT ON TABLE SIBDBA.V_ONLINE_LINKAGE IS 'COMMENTAIRE:
Vue permettant de montrer les métadonnées de type ONLINE_LINKAGE.';



CREATE OR REPLACE PUBLIC SYNONYM V_ONLINE_LINKAGE FOR SIBDBA.V_ONLINE_LINKAGE;


GRANT SELECT ON SIBDBA.V_ONLINE_LINKAGE TO MDDTN;

GRANT SELECT ON SIBDBA.V_ONLINE_LINKAGE TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_ONLINE_LINKAGE TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_ONLINE_LINKAGE TO SIBMAJ;
