DROP VIEW SIBDBA.V_OVERVIEW;

/* Formatted on 2013/12/23 11:00:46 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_OVERVIEW
(
   TY_PRODUIT,
   IDENTIFIANT,
   ED,
   VER,
   OVERVIEW,
   CITATION,
   LIEN
)
AS
   SELECT A.TY_PRODUIT,
          A.IDENTIFIANT,
          A.ED,
          A.VER,
          A.OVERVIEW,
          B.CITATION,
          A.TY_PRODUIT || '-' || A.IDENTIFIANT || '-' || A.ED || '.' || A.VER
     FROM F235_OD A, F235_DC B
    WHERE     A.TY_PRODUIT = B.TY_PRODUIT
          AND A.IDENTIFIANT = B.IDENTIFIANT
          AND A.ED = B.ED
          AND A.VER = B.VER
          AND A.OVERVIEW = B.OVERVIEW;

COMMENT ON TABLE SIBDBA.V_OVERVIEW IS 'COMMENTAIRE:
Vue permettant de montrer les métadonnées de type OVERVIEW.';



CREATE OR REPLACE PUBLIC SYNONYM V_OVERVIEW FOR SIBDBA.V_OVERVIEW;


GRANT SELECT ON SIBDBA.V_OVERVIEW TO MDDTN;

GRANT SELECT ON SIBDBA.V_OVERVIEW TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_OVERVIEW TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_OVERVIEW TO SIBMAJ;
