DROP VIEW SIBDBA.V_PLANAR;

/* Formatted on 2013/12/23 11:01:44 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_PLANAR
(
   TY_PRODUIT,
   IDENTIFIANT,
   ED,
   VER,
   NO_SEQ,
   ENCODING_METHOD,
   DISTANCE_UNITS,
   ABSCISSA_RES,
   ORDINATE_RES,
   UTM_ZONE,
   UTM_SCALE_FACTOR_CENT_MERID,
   UTM_LON_CENTRAL_MERIDIAN,
   UTM_LAT_PROJ_ORIGIN,
   UTM_FALSE_EASTING,
   UTM_FALSE_NORTHING,
   LCC_STD_PARALLEL_1,
   LCC_STD_PARALLEL_2,
   LCC_LON_CENTRAL_MERIDIAN,
   LCC_LAT_PROJ_ORIGIN,
   LCC_FALSE_EASTING,
   LCC_FALSE_NORTHING,
   LIEN
)
AS
   SELECT A.TY_PRODUIT,
          A.IDENTIFIANT,
          A.ED,
          A.VER,
          A.NO_SEQ,
          A.ENCODING_METHOD,
          A.DISTANCE_UNITS,
          A.ABSCISSA_RES,
          A.ORDINATE_RES,
          B.UTM_ZONE,
          B.SCALE_FACTOR_CENT_MERID,
          B.LON_CENTRAL_MERIDIAN,
          B.LAT_PROJ_ORIGIN,
          B.FALSE_EASTING,
          B.FALSE_NORTHING,
          C.STD_PARALLEL_1,
          C.STD_PARALLEL_2,
          C.LON_CENTRAL_MERIDIAN,
          C.LAT_PROJ_ORIGIN,
          C.FALSE_EASTING,
          C.FALSE_NORTHING,
          A.TY_PRODUIT || '-' || A.IDENTIFIANT || '-' || A.ED || '.' || A.VER
     FROM F235_PL A, F235_UT B, F235_LC C
    WHERE     A.TY_PRODUIT = B.TY_PRODUIT(+)
          AND A.IDENTIFIANT = B.IDENTIFIANT(+)
          AND A.ED = B.ED(+)
          AND A.VER = B.VER(+)
          AND A.NO_SEQ = B.NO_SEQ(+)
          AND A.TY_PRODUIT = C.TY_PRODUIT(+)
          AND A.IDENTIFIANT = C.IDENTIFIANT(+)
          AND A.ED = C.ED(+)
          AND A.VER = C.VER(+)
          AND A.NO_SEQ = C.NO_SEQ(+);

COMMENT ON TABLE SIBDBA.V_PLANAR IS 'COMMENTAIRE:
Vue permettant de montrer les métadonnées de type PLANAR.';



CREATE OR REPLACE PUBLIC SYNONYM V_PLANAR FOR SIBDBA.V_PLANAR;


GRANT SELECT ON SIBDBA.V_PLANAR TO MDDTN;

GRANT SELECT ON SIBDBA.V_PLANAR TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_PLANAR TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_PLANAR TO SIBMAJ;
