DROP VIEW SIBDBA.V_PRODUCTION_COURANTE;

/* Formatted on 2014-12-03 16:59:59 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_PRODUCTION_COURANTE
(
   NO_MAP,
   NO_LOT,
   GROUPE,
   TY_TRAV,
   TY_PRODUIT,
   NORMES,
   IDENTIFIANT,
   ED,
   VER,
   CD_EQUIPE,
   CD_EXECU,
   DT_PREVUE,
   DT_FIN_GRP,
   DT_FIN,
   CONTENU,
   PRECISION,
   ETAT
)
AS
   SELECT DISTINCT CAST (F502_PS.NO_MAP AS NUMBER (10)),
                   F503_TR.NO_LOT,
                   F503_TR.GROUPE,
                   F503_TR.TY_TRAV,
                   F502_PS.TY_PRODUIT,
                   F502_PS.NORMES,
                   F502_PS.IDENTIFIANT,
                   F502_PS.ED,
                   F502_PS.VER,
                   F601_LO.CD_EQUIPE,
                   F601_LO.CD_EXECU,
                   TO_DATE (F502_PS.DT_PREVUE) AS DT_PREVUE,
                   TO_DATE (F601_LO.DT_FIN) AS DT_FIN_GRP,
                   TO_DATE (V503_TR_DT_FIN.DT_FIN) AS DT_FIN,
                   F601_GR.QUAL_CONTENU CONTENU,
                   F601_GR.PREC_DEFICIENTE PRECISION,
                   F502_PS.E_PLSNRC ETAT
     FROM F502_PS,
          F503_TR,
          F601_LO,
          F601_GR,
          V503_TR_DT_FIN
    WHERE     F502_PS.E_PLSNRC = 'P'
          AND F502_PS.NO_MAP = F503_TR.NO_MAP
          AND F503_TR.NO_LOT = F601_LO.NO_LOT
          AND F503_TR.NO_LOT = F601_GR.NO_LOT
          AND F503_TR.GROUPE = F601_GR.GROUPE
          AND V503_TR_DT_FIN.NO_MAP = F502_PS.NO_MAP
          AND V503_TR_DT_FIN.TY_TRAV = F503_TR.TY_TRAV;

COMMENT ON TABLE SIBDBA.V_PRODUCTION_COURANTE IS 'COMMENTAIRE:
Vue permettant de montrer la production courante.';

CREATE OR REPLACE PUBLIC SYNONYM V_PRODUCTION_COURANTE FOR SIBDBA.V_PRODUCTION_COURANTE;

GRANT SELECT ON SIBDBA.V_PRODUCTION_COURANTE TO MDDTN;

GRANT SELECT ON SIBDBA.V_PRODUCTION_COURANTE TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_PRODUCTION_COURANTE TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_PRODUCTION_COURANTE TO SIBMAJ;
