DROP VIEW SIBDBA.V_SOURCES;

/* Formatted on 2013/12/23 11:03:32 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_SOURCES
(
   TY_PRODUIT,
   IDENTIFIANT,
   ED,
   VER,
   TY_PRODUIT_SRCE,
   IDENTIFIANT_SRCE,
   ED_SRCE,
   VER_SRCE,
   DT_PUBLICATION,
   DT_VALID_DEB,
   DT_VALID_FIN,
   TY_MEDIA,
   CURRENTNESS_REF,
   ABR,
   CONTRIBUTION,
   SERIES_NAME,
   ISSUE_ID,
   ORIGINATOR,
   LIEN
)
AS
   SELECT A.TY_PRODUIT,
          A.IDENTIFIANT,
          A.ED,
          A.VER,
          A.TY_PRODUIT_SRCE,
          A.IDENTIFIANT_SRCE,
          A.ED_SRCE,
          A.VER_SRCE,
          A.DT_PUBLICATION,
          A.DT_VALID_DEB,
          A.DT_VALID_FIN,
          A.TY_MEDIA,
          A.CURRENTNESS_REF,
          A.ABR,
          A.CONTRIBUTION,
          A.SERIES_NAME,
          A.ISSUE_ID,
          B.ORIGINATOR,
          A.TY_PRODUIT || '-' || A.IDENTIFIANT || '-' || A.ED || '.' || A.VER
     FROM F235_SC A, F235_SO B
    WHERE     A.TY_PRODUIT = B.TY_PRODUIT
          AND A.IDENTIFIANT = B.IDENTIFIANT
          AND A.ED = B.ED
          AND A.VER = B.VER
          AND A.TY_PRODUIT_SRCE = B.TY_PRODUIT_SRCE
          AND A.IDENTIFIANT_SRCE = B.IDENTIFIANT_SRCE
          AND A.ED_SRCE = B.ED_SRCE
          AND A.VER_SRCE = B.VER_SRCE;

COMMENT ON TABLE SIBDBA.V_SOURCES IS 'COMMENTAIRE:
Vue permettant de montrer les métadonnées de type SOURCES.';



CREATE OR REPLACE PUBLIC SYNONYM V_SOURCES FOR SIBDBA.V_SOURCES;


GRANT SELECT ON SIBDBA.V_SOURCES TO MDDTN;

GRANT SELECT ON SIBDBA.V_SOURCES TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_SOURCES TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_SOURCES TO SIBMAJ;
