DROP VIEW SIBDBA.V_SUIVI_PRODUCTION;

/* Formatted on 2014-08-18 15:33:24 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_SUIVI_PRODUCTION
(
   NO_MAP,
   NO_LOT,
   TY_PRODUIT,
   IDENTIFIANT,
   TY_TRAV,
   CD_ETP,
   NOM_ETP,
   NO_SEQ_ETP,
   NO_SEQ_ITER,
   CD_OPER,
   PRENOM,
   NOM,
   ITERATIVE,
   FLOTTANTE,
   DT_FIN_ETP,
   DT_RECU,
   DT_DEB,
   DT_FIN,
   DELAI,
   ACCEPTE
)
AS
   SELECT F602_ET.NO_MAP,
          F602_ET.NO_LOT,
          F502_PS.TY_PRODUIT,
          F502_PS.IDENTIFIANT,
          F601_LO.TY_TRAV,
          F602_ET.CD_ETP,
          F117_ET.NOM AS NOM_ETP,
          F602_ET.NO_SEQ AS NO_SEQ_ETP,
          F603_IT.NO_SEQ AS NO_SEQ_ITER,
          F602_ET.CD_OPER,
          F005_US.PRENOM,
          F005_US.NOM,
          F606_GE.ITERATIVE,
          F606_GE.FLOTTANTE,
          TO_DATE (F602_ET.DT_FIN_ETP) DT_FIN_ETP,
          F603_IT.DT_RECU,
          F603_IT.DT_DEB,
          F603_IT.DT_FIN,
          V603_IT_DELAI.DELAI,
          F603_IT.ACCEPTE
     FROM F502_PS,
          F601_LO,
          F606_GE,
          F117_ET,
          F005_US,
          F602_ET,
          F603_IT,
          V603_IT_DELAI
    WHERE     F602_ET.NO_MAP = F603_IT.NO_MAP(+)
          AND F602_ET.NO_MAP = V603_IT_DELAI.NO_MAP(+)
          AND F602_ET.CD_ETP = F603_IT.CD_ETP(+)
          AND F602_ET.CD_ETP = V603_IT_DELAI.CD_ETP(+)
          AND F603_IT.NO_SEQ = V603_IT_DELAI.NO_SEQ
          AND F602_ET.NO_MAP = F502_PS.NO_MAP
          AND F602_ET.NO_LOT = F601_LO.NO_LOT
          AND F602_ET.NO_LOT = F606_GE.NO_LOT
          AND F602_ET.CD_ETP = F606_GE.CD_ETP
          AND F602_ET.CD_ETP = F117_ET.CD_ETP
          AND F602_ET.CD_OPER = F005_US.CD_USER_AB(+);

COMMENT ON TABLE SIBDBA.V_SUIVI_PRODUCTION IS 'COMMENTAIRE:
Vue permettant de montrer le suivi de production complet.';

CREATE OR REPLACE PUBLIC SYNONYM V_SUIVI_PRODUCTION FOR SIBDBA.V_SUIVI_PRODUCTION;

GRANT SELECT ON SIBDBA.V_SUIVI_PRODUCTION TO MDDTN;

GRANT SELECT ON SIBDBA.V_SUIVI_PRODUCTION TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_SUIVI_PRODUCTION TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_SUIVI_PRODUCTION TO SIBMAJ;
