/* Formatted on 2014-11-21 11:56:22 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW V_USAGERS
(
   CD_USER,
   NOM,
   PRENOM,
   ACTIF
)
AS
   SELECT CD_USER,
          NOM,
          PRENOM,
          ACTIF
     FROM F005_US;

COMMENT ON TABLE V_USAGERS IS 'COMMENTAIRE:
Vue permettant de montrer les usagers SIB sans le mot de passe.';

CREATE OR REPLACE PUBLIC SYNONYM V_USAGERS FOR V_USAGERS;

GRANT SELECT ON V_USAGERS TO MDDTN;

GRANT SELECT ON V_USAGERS TO SIBLIRE;

GRANT SELECT ON V_USAGERS TO SIBLIREDIFF;

GRANT SELECT ON V_USAGERS TO SIBMAJ;