DROP VIEW SIBDBA.V_VERTICAL_ACCURACY;

/* Formatted on 2013/12/23 11:05:44 (QP5 v5.240.12305.39446) */
CREATE OR REPLACE FORCE VIEW SIBDBA.V_VERTICAL_ACCURACY
(
   TY_PRODUIT,
   IDENTIFIANT,
   ED,
   VER,
   REPORT,
   NO_SEQ,
   VALUE,
   EXPLANATION,
   LIEN
)
AS
   SELECT A.TY_PRODUIT,
          A.IDENTIFIANT,
          A.ED,
          A.VER,
          A.REPORT,
          B.NO_SEQ,
          B.VALUE,
          B.EXPLANATION,
          A.TY_PRODUIT || '-' || A.IDENTIFIANT || '-' || A.ED || '.' || A.VER
     FROM F235_PV A, F235_AV B
    WHERE     A.TY_PRODUIT = B.TY_PRODUIT
          AND A.IDENTIFIANT = B.IDENTIFIANT
          AND A.ED = B.ED
          AND A.VER = B.VER;

COMMENT ON TABLE SIBDBA.V_VERTICAL_ACCURACY IS 'COMMENTAIRE:
Vue permettant de montrer les métadonnées de type VERTICAL_ACCURACY.';



CREATE OR REPLACE PUBLIC SYNONYM V_VERTICAL_ACCURACY FOR SIBDBA.V_VERTICAL_ACCURACY;


GRANT SELECT ON SIBDBA.V_VERTICAL_ACCURACY TO MDDTN;

GRANT SELECT ON SIBDBA.V_VERTICAL_ACCURACY TO SIBLIRE;

GRANT SELECT ON SIBDBA.V_VERTICAL_ACCURACY TO SIBLIREDIFF;

GRANT SELECT ON SIBDBA.V_VERTICAL_ACCURACY TO SIBMAJ;
